// Seed data — realistic Polish homebrewing context
const RECIPES = [
  {
    id: "r1",
    name: "Chmielowa Mgła",
    nameEn: "Hopfog",
    style: "American Pale Ale",
    bjcp: "18B",
    version: 7,
    brewCount: 4,
    lastBrewed: "2026-03-12",
    author: "Ty",
    color: "#D4A574",
    volume: 23,
    boilTime: 60,
    efficiency: 72,
    targets: { og: 1.052, fg: 1.011, abv: 5.4, ibu: 38, ebc: 12, srm: 6 },
    grainBill: [
      { id: "g1", name: "Pale Ale malt", origin: "Weyermann", qty: 4.2, pct: 78, ebc: 7 },
      { id: "g2", name: "Monachijski jasny", origin: "Weyermann", qty: 0.6, pct: 11, ebc: 15 },
      { id: "g3", name: "Caramel 60L", origin: "Briess", qty: 0.35, pct: 7, ebc: 120 },
      { id: "g4", name: "Płatki owsiane", origin: "—", qty: 0.2, pct: 4, ebc: 4 },
    ],
    hops: [
      { id: "h1", name: "Magnum", type: "bittering", alpha: 13.2, qty: 15, time: 60 },
      { id: "h2", name: "Citra", type: "flavor", alpha: 12.0, qty: 20, time: 15 },
      { id: "h3", name: "Simcoe", type: "aroma", alpha: 12.8, qty: 25, time: 5 },
      { id: "h4", name: "Citra", type: "whirlpool", alpha: 12.0, qty: 30, time: 20 },
      { id: "h5", name: "Mosaic", type: "dryHop", alpha: 11.5, qty: 40, time: 3 },
      { id: "h6", name: "Citra", type: "dryHop", alpha: 12.0, qty: 40, time: 3 },
    ],
    yeast: {
      strain: "Fermentis SafAle US-05",
      attenuation: 81,
      flocculation: "średnia",
      tempMin: 15, tempMax: 22,
      pitchTemp: 19,
    },
    mash: [
      { id: "m1", name: "Przerwa białkowa", temp: 52, duration: 15, ramp: 1 },
      { id: "m2", name: "Przerwa maltozowa", temp: 63, duration: 30, ramp: 1 },
      { id: "m3", name: "Przerwa scukrzająca", temp: 72, duration: 30, ramp: 1 },
      { id: "m4", name: "Mash-out", temp: 78, duration: 10, ramp: 1 },
    ],
    fermentation: [
      { phase: "primary", temp: 19, days: 7 },
      { phase: "dryHop", temp: 20, days: 3 },
      { phase: "conditioning", temp: 2, days: 14 },
    ],
    adjuncts: [
      { name: "Węglan wapnia", qty: "3 g" },
      { name: "Siarczan wapnia (gips)", qty: "6 g" },
    ],
    water: {
      profile: "Burton-on-Trent (zmiękczony)",
      ca: 120, mg: 10, na: 25, so4: 180, cl: 50, hco3: 40, ph: 5.4,
    },
    history: [
      { v: 7, date: "2026-03-12", note: "Zwiększono dry hop z 70g → 80g. Mosaic zamiast Amarillo." },
      { v: 6, date: "2025-11-02", note: "Zmiana drożdży z Voss na US-05 dla czystszego profilu." },
      { v: 5, date: "2025-07-14", note: "Dodano płatki owsiane dla pełniejszego body." },
    ],
  },
  {
    id: "r2",
    name: "Hetman",
    nameEn: "Hetman",
    style: "Czech Premium Pale Lager",
    bjcp: "3B",
    version: 3,
    brewCount: 2,
    lastBrewed: "2026-02-08",
    author: "Ty",
    color: "#E8B75D",
    volume: 25,
    boilTime: 90,
    efficiency: 75,
    targets: { og: 1.050, fg: 1.012, abv: 5.0, ibu: 35, ebc: 10, srm: 5 },
    grainBill: [
      { id: "g1", name: "Pilzneński", origin: "Weyermann", qty: 4.8, pct: 96, ebc: 3 },
      { id: "g2", name: "Caraphils", origin: "Weyermann", qty: 0.2, pct: 4, ebc: 5 },
    ],
    hops: [
      { id: "h1", name: "Saaz", type: "bittering", alpha: 3.8, qty: 35, time: 60 },
      { id: "h2", name: "Saaz", type: "flavor", alpha: 3.8, qty: 25, time: 30 },
      { id: "h3", name: "Saaz", type: "aroma", alpha: 3.8, qty: 25, time: 5 },
    ],
    yeast: { strain: "Wyeast 2124 Bohemian Lager", attenuation: 75, flocculation: "wysoka", tempMin: 9, tempMax: 13, pitchTemp: 10 },
    mash: [
      { id: "m1", name: "Ferulic rest", temp: 45, duration: 15, ramp: 1 },
      { id: "m2", name: "Przerwa maltozowa", temp: 62, duration: 40, ramp: 1 },
      { id: "m3", name: "Przerwa scukrzająca", temp: 72, duration: 20, ramp: 1 },
      { id: "m4", name: "Mash-out", temp: 78, duration: 10, ramp: 1 },
    ],
    fermentation: [{ phase: "primary", temp: 10, days: 14 }, { phase: "conditioning", temp: 1, days: 42 }],
    adjuncts: [],
    water: { profile: "Pilzno (miękka)", ca: 7, mg: 3, na: 5, so4: 5, cl: 5, hco3: 15, ph: 5.3 },
    history: [{ v: 3, date: "2026-02-08", note: "Wydłużone leżakowanie do 6 tygodni." }],
  },
  {
    id: "r3",
    name: "Dąb i Dym",
    nameEn: "Oak & Smoke",
    style: "Rauchbier / Smoked Porter",
    bjcp: "27",
    version: 2,
    brewCount: 1,
    lastBrewed: "2025-12-20",
    author: "Ty",
    color: "#3A1F10",
    volume: 20,
    boilTime: 60,
    efficiency: 70,
    targets: { og: 1.058, fg: 1.014, abv: 5.8, ibu: 28, ebc: 78, srm: 30 },
    grainBill: [],
    hops: [], yeast: { strain: "", attenuation: 0, flocculation: "", tempMin: 0, tempMax: 0, pitchTemp: 0 },
    mash: [], fermentation: [], adjuncts: [], water: {},
    history: [],
  },
  {
    id: "r4",
    name: "Pani Wiosno",
    nameEn: "Lady Spring",
    style: "Hefeweizen",
    bjcp: "10A",
    version: 4,
    brewCount: 3,
    lastBrewed: "2026-04-01",
    author: "Ty",
    color: "#D89A3E",
    volume: 20,
    boilTime: 60,
    efficiency: 73,
    targets: { og: 1.050, fg: 1.011, abv: 5.1, ibu: 14, ebc: 14, srm: 7 },
    grainBill: [], hops: [], yeast: { strain: "", attenuation: 0, flocculation: "", tempMin: 0, tempMax: 0, pitchTemp: 0 },
    mash: [], fermentation: [], adjuncts: [], water: {}, history: [],
  },
];

const MATERIALS = {
  malt: [
    { id: "ml1", name: "Pale Ale malt", supplier: "Weyermann", origin: "DE", ebc: 6.5, stock: 18.4, unit: "kg", usedIn: ["r1"], price: 8.5, purchased: "2026-03-01" },
    { id: "ml2", name: "Pilzneński", supplier: "Weyermann", origin: "DE", ebc: 3.2, stock: 12.0, unit: "kg", usedIn: ["r2"], price: 8.0, purchased: "2026-02-20" },
    { id: "ml3", name: "Monachijski jasny", supplier: "Weyermann", origin: "DE", ebc: 15, stock: 5.2, unit: "kg", usedIn: ["r1"], price: 9.0, purchased: "2026-03-01" },
    { id: "ml4", name: "Caramel 60L", supplier: "Briess", origin: "US", ebc: 120, stock: 1.1, unit: "kg", usedIn: ["r1"], price: 12, purchased: "2026-02-12" },
    { id: "ml5", name: "Wędzony bukowy", supplier: "Weyermann", origin: "DE", ebc: 5, stock: 0.8, unit: "kg", usedIn: ["r3"], price: 14, purchased: "2025-11-10" },
    { id: "ml6", name: "Czekoladowy", supplier: "Thomas Fawcett", origin: "UK", ebc: 800, stock: 0.4, unit: "kg", usedIn: ["r3"], price: 16, purchased: "2025-11-10" },
    { id: "ml7", name: "Pszeniczny jasny", supplier: "Weyermann", origin: "DE", ebc: 4, stock: 4.5, unit: "kg", usedIn: ["r4"], price: 9, purchased: "2026-03-20" },
  ],
  hop: [
    { id: "hp1", name: "Citra", supplier: "Yakima Chief", origin: "US", alpha: 12.0, stock: 180, unit: "g", usedIn: ["r1"], price: 0.35, purchased: "2026-03-01" },
    { id: "hp2", name: "Mosaic", supplier: "Yakima Chief", origin: "US", alpha: 11.5, stock: 120, unit: "g", usedIn: ["r1"], price: 0.38, purchased: "2026-03-01" },
    { id: "hp3", name: "Simcoe", supplier: "Yakima Chief", origin: "US", alpha: 12.8, stock: 75, unit: "g", usedIn: ["r1"], price: 0.36, purchased: "2026-02-12" },
    { id: "hp4", name: "Magnum", supplier: "Hopsteiner", origin: "DE", alpha: 13.2, stock: 60, unit: "g", usedIn: ["r1"], price: 0.20, purchased: "2026-01-20" },
    { id: "hp5", name: "Saaz", supplier: "Bohemia", origin: "CZ", alpha: 3.8, stock: 30, unit: "g", usedIn: ["r2"], price: 0.28, purchased: "2026-01-20", lowStock: true },
    { id: "hp6", name: "Tettnanger", supplier: "Hopsteiner", origin: "DE", alpha: 4.5, stock: 0, unit: "g", usedIn: [], price: 0.30, purchased: "—" },
  ],
  yeast: [
    { id: "y1", name: "SafAle US-05", supplier: "Fermentis", origin: "FR", attenuation: 81, stock: 4, unit: "szt.", usedIn: ["r1"], price: 14, purchased: "2026-03-01" },
    { id: "y2", name: "Wyeast 2124 Bohemian Lager", supplier: "Wyeast", origin: "US", attenuation: 75, stock: 1, unit: "szt.", usedIn: ["r2"], price: 42, purchased: "2026-02-01", lowStock: true },
    { id: "y3", name: "WB-06 Weizen", supplier: "Fermentis", origin: "FR", attenuation: 86, stock: 2, unit: "szt.", usedIn: ["r4"], price: 14, purchased: "2026-03-20" },
  ],
  adjunct: [
    { id: "a1", name: "Gips (CaSO₄)", supplier: "BrewChem", origin: "PL", stock: 500, unit: "g", usedIn: ["r1"], price: 0.05, purchased: "2025-09-10" },
    { id: "a2", name: "Kwas mlekowy 80%", supplier: "BrewChem", origin: "PL", stock: 180, unit: "ml", usedIn: ["r1", "r2"], price: 0.08, purchased: "2025-09-10" },
    { id: "a3", name: "Whirlfloc", supplier: "Kerry", origin: "IE", stock: 25, unit: "tabl.", usedIn: ["r1", "r2"], price: 1.2, purchased: "2025-11-10" },
  ],
};

const SUBMISSIONS = [
  { id: "s1", name: "Polaris", category: "hop", note: "Chmiel niemiecki, 19–23% α-kwasy, silnie miętowo-eukaliptusowy. Potrzebne w bazie.", submittedBy: "Ty", submittedAt: "2026-04-10", status: "pending" },
  { id: "s2", name: "Malt Carabohemian", category: "malt", note: "EBC ~160, karmel czeski. Brakuje w katalogu systemu.", submittedBy: "Ty", submittedAt: "2026-04-05", status: "pending" },
  { id: "s3", name: "Kveik Voss", category: "yeast", note: "Szczep norweski, atenuacja 80%, tolerancja 38°C.", submittedBy: "admin", submittedAt: "2026-03-22", status: "approved" },
];

// Active brew session
const ACTIVE_SESSION = {
  id: "bs1",
  recipeId: "r1",
  startedAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(), // started 42 min ago
  currentStep: "mash",
  stepIndex: 1,
  steps: [
    { key: "mashIn", label: "Zasyp", status: "done", actualStart: "-00:42", actualEnd: "-00:32", plannedDuration: 10, actualDuration: 10 },
    { key: "mash", label: "Zacieranie", status: "active", actualStart: "-00:32", plannedDuration: 85, elapsedMin: 32, subSteps: [
      { name: "Przerwa białkowa 52°C", status: "done", plannedTemp: 52, actualTemp: 52.4, plannedDur: 15, actualDur: 15 },
      { name: "Przerwa maltozowa 63°C", status: "done", plannedTemp: 63, actualTemp: 62.8, plannedDur: 30, actualDur: 32 },
      { name: "Przerwa scukrzająca 72°C", status: "active", plannedTemp: 72, actualTemp: 71.6, plannedDur: 30, elapsedDur: 14 },
      { name: "Mash-out 78°C", status: "pending", plannedTemp: 78, plannedDur: 10 },
    ]},
    { key: "lauter", label: "Filtracja", status: "pending", plannedDuration: 45 },
    { key: "boil", label: "Gotowanie", status: "pending", plannedDuration: 60 },
    { key: "hop", label: "Chmielenie", status: "pending", plannedDuration: 60, nested: true },
    { key: "chill", label: "Schładzanie", status: "pending", plannedDuration: 25 },
    { key: "pitch", label: "Zadanie drożdży", status: "pending", plannedDuration: 5 },
    { key: "ferment", label: "Fermentacja", status: "pending", plannedDuration: 60 * 24 * 7 },
  ],
  sanitation: [
    { id: "c1", label: "Kadź zacierna — gorąca woda + StarSan", done: true },
    { id: "c2", label: "Kadź warzelna — przepłukana", done: true },
    { id: "c3", label: "Fermentor — StarSan 2 min", done: true },
    { id: "c4", label: "Bełkotka / aerator — StarSan", done: false },
    { id: "c5", label: "Termometr / areometr — alcohol wipe", done: true },
    { id: "c6", label: "Rurka fermentacyjna + korek", done: false },
    { id: "c7", label: "Naczynia do pomiarów", done: false },
  ],
  measurements: [
    { id: "mm1", label: "Woda do zacierania (temp.)", value: 68.5, unit: "°C", time: "-00:44" },
    { id: "mm2", label: "pH zacieru", value: 5.35, unit: "pH", time: "-00:18" },
    { id: "mm3", label: "Temp. w przerwie maltozowej", value: 62.8, unit: "°C", time: "-00:12" },
  ],
  events: [
    { id: "e1", time: "-00:42", note: "Start. Woda dojechała do 68°C, zasyp słodów.", kind: "step" },
    { id: "e2", time: "-00:35", note: "Dobra konsystencja zacieru. Dodano 3g gipsu.", kind: "note" },
    { id: "e3", time: "-00:30", note: "Przerwa białkowa 52°C — utrzymuję 15 min.", kind: "step" },
    { id: "e4", time: "-00:14", note: "Jodyna → czysto, skrobia scukrzona.", kind: "note" },
    { id: "e5", time: "-00:08", note: "Palnik jedzie w drugą pozycję — narost do 72°C.", kind: "note" },
  ],
};

window.DB = { RECIPES, MATERIALS, SUBMISSIONS, ACTIVE_SESSION };
